name: minezweeper
description: MineSweeper Game.
publish_to: 'none'

version: 0.2.4+8

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^5.6.10
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.0
  firebase_crashlytics: ^4.3.8
  flex_color_scheme: ^8.2.0
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.3.0
  intl: any
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  assets:
    - asset/png/
    - asset/google_font/
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#e89ca1"
  image: asset/png/logo.png
  color_dark: "#a26457"
  image_dark: asset/png/logo.png
